filtering: filtering.c
	gcc filtering.c -o filtering

sortingScores: sortingScores.c
	gcc sortingScores.c -o sortingScores

sortingStrings: sortingStrings.c
	gcc sortingStrings.c -o sortingStrings

enums: enums.c
	gcc enums.c -o enums

flexibleParams: flexibleParams.c
	gcc flexibleParams.c -o flexibleParams