linkedList: linkedList.c
	gcc linkedList.c -o linkedList

dynamicMemory: dynamicMemory.c
	gcc dynamicMemory.c -o dynamicMemory

sips: sips.c
	gcc sips.c -o sips

debug sips: sips.c
	gcc -g sips.c -o sips